---
- name: Install IIS 10 on Windows Server .
  hosts: windows
  gather_facts: no
  vars:
    zip_url: "https://10.32.20.128/public-archives/download/IIS2019/IIS10_2019.zip"
    zip_dest_path: "D:\\IIS10_2019.zip"
    extract_dir: "D:\\IIS10"
    scripts_src: "files/iis/"
    scripts_dest: "D:\\iis"
    min_free_gb: 100

  tasks:
    - name: Assert D: drive exists
      ansible.windows.win_stat:
        path: "D:\\"
      register: d_drive

    - name: Fail if D: drive is missing
      ansible.builtin.fail:
        msg: "D: drive is required but not present."
      when: not d_drive.stat.exists

    - name: Get free space on D: drive (GB)
      ansible.windows.win_shell: |
        $drive = Get-PSDrive -Name D -ErrorAction Stop
        [math]::Floor($drive.Free / 1GB)
      register: d_free_gb

    - name: Validate free space on D: drive
      ansible.builtin.fail:
        msg: "D: drive requires at least {{ min_free_gb }} GB free. Found {{ d_free_gb.stdout | default('unknown') }} GB."
      when: (d_free_gb.rc != 0) or ((d_free_gb.stdout | int) < min_free_gb)

    - name: Ensure extract directory exists
      ansible.windows.win_file:
        path: "{{ extract_dir }}"
        state: directory

    - name: Download IIS package zip
      ansible.windows.win_get_url:
        url: "{{ zip_url }}"
        dest: "{{ zip_dest_path }}"
        validate_certs: no

    - name: Unzip IIS package
      community.windows.win_unzip:
        src: "{{ zip_dest_path }}"
        dest: "{{ extract_dir }}"
        delete_archive: no


