---
- name: Create ServiceNow Change Request via REST API
  hosts: all
  gather_facts: no
  vars:
    servicenow_instance: "{{ lookup('cypher','secret=secret/snowinstance') }}"
    servicenow_user: "admin"
    servicenow_password: "VfHeoXw9$3%T"
    change_request_payload:
      short_description: "Update Apache Server"
      description: "Updating Apache server to latest stable version"
      category: "Software"
      priority: "3"
      risk: "Low"
      type: "Normal"

  tasks:
    - name: Create a Change Request in ServiceNow
      uri:
        url: "https://{{ servicenow_instance }}/api/now/table/change_request"
        method: POST
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body: "{{ change_request_payload }}"
        status_code: 201
      register: create_response
      ignore_errors: yes

    - name: Display full API response
      debug:
        var: create_response
