---
- name: Override primary and secondary DNS on RHEL 9
  hosts: rhel9_servers
  become: yes
  vars:
    primary_dns: "8.8.8.8"
    secondary_dns: "8.8.4.4"

  tasks:
    - name: Get active NetworkManager connections
      command: nmcli -t -f NAME connection show --active
      register: active_conns
      changed_when: false

    - name: Set DNS servers for active connections
      community.general.nmcli:
        type: ethernet
        conn_name: "{{ item }}"
        dns4:
          - "{{ primary_dns }}"
          - "{{ secondary_dns }}"
        state: present
      loop: "{{ active_conns.stdout_lines }}"

    - name: Restart NetworkManager to apply changes
      systemd:
        name: NetworkManager
        state: restarted
