---
- name: Set IPv4 DNS and search domain on RHEL 9 reliably (nmcli only)
  hosts: all
  become: yes
  vars:
    ipv4_dns: "8.8.8.8 8.8.4.4"
    search_domain: "test.com"

  tasks:
    - name: Get active NetworkManager connection names
      command: nmcli -t -f NAME,TYPE connection show --active
      register: active_conns
      changed_when: false

    - name: Apply IPv4 DNS and search domain
      shell: |
        nmcli connection modify "{{ item }}" ipv4.dns "{{ ipv4_dns }}"
        nmcli connection modify "{{ item }}" ipv4.dns-search "{{ search_domain }}"
        nmcli connection modify "{{ item }}" ipv4.ignore-auto-dns yes
      loop: "{{ active_conns.stdout_lines | map('split', ':') | map('first') | list }}"
      notify: Reload NM connection

    - name: Flush systemd-resolved DNS cache (if present)
      command: resolvectl flush-caches
      ignore_errors: yes

  handlers:
    - name: Reload NM connection
      shell: nmcli connection up "{{ item }}"
      loop: "{{ active_conns.stdout_lines | map('split', ':') | map('first') | list }}"
