---
- name: Set IPv4 DNS and search domain on RHEL-family hosts
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ipv4_dns: "8.8.8.0 8.8.1.1"  #  can be replaced with form input  {{ morpheus['customOptions']['varname'] }}
    search_domain: "test.com"  #  can be replaced with form input  {{ morpheus['customOptions']['varname'] }}

  tasks:
    - name: Get active NetworkManager connection names
      command: nmcli -t -f NAME,TYPE connection show --active
      register: active_conns
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Apply IPv4 DNS and search domain
      shell: |
        nmcli connection modify "{{ item }}" ipv4.dns "{{ ipv4_dns }}"
        nmcli connection modify "{{ item }}" ipv4.dns-search "{{ search_domain }}"
        nmcli connection modify "{{ item }}" ipv4.ignore-auto-dns yes
      loop: "{{ active_conns.stdout_lines | map('split', ':') | map('first') | list }}"
      when: ansible_os_family == "RedHat"
      notify: Reload NM connection

    - name: Flush systemd-resolved DNS cache (if present)
      command: resolvectl flush-caches
      ignore_errors: yes
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Reload NM connection
      shell: nmcli connection up "{{ item }}"
      loop: "{{ active_conns.stdout_lines | map('split', ':') | map('first') | list }}"
      when: ansible_os_family == "RedHat"
