---
- name: Set IPv4 DNS and search domain on RHEL 9 (IPv6 ignored)
  hosts: all
  become: yes
  vars:
    ipv4_dns: "8.8.8.8 8.8.4.4"
    search_domain: "example.com"

  tasks:
    - name: Get active NetworkManager connection names
      command: nmcli -t -f NAME connection show --active
      register: active_conns
      changed_when: false

    - name: Remove existing IPv4 DNS and set new DNS + search domain
      shell: |
        nmcli connection modify "{{ item }}" ipv4.dns ""
        nmcli connection modify "{{ item }}" ipv4.dns "{{ ipv4_dns }}"
        nmcli connection modify "{{ item }}" ipv4.dns-search "{{ search_domain }}"
        nmcli connection modify "{{ item }}" ipv4.ignore-auto-dns yes
        nmcli connection modify "{{ item }}" ipv4.method manual
      loop: "{{ active_conns.stdout_lines }}"

    - name: Reactivate connections to apply changes
      shell: nmcli connection down "{{ item }}" && nmcli connection up "{{ item }}"
      loop: "{{ active_conns.stdout_lines }}"

    - name: Verify applied IPv4 DNS and search domain
      command: nmcli connection show "{{ item }}"
      loop: "{{ active_conns.stdout_lines }}"
      register: nmcli_verify

    - name: Print applied IPv4 DNS and search domain
      debug:
        msg: "{{ item.stdout_lines | select('search','dns') | list }}"
      loop: "{{ nmcli_verify.results }}"
