---
- name: Remove existing DNS, set new DNS and domain on RHEL 9
  hosts: all
  become: yes
  vars:
    primary_dns: "8.8.8.8"
    secondary_dns: "8.8.4.4"
    search_domain: "example.com"

  tasks:
    - name: Get active NetworkManager connection names
      command: nmcli -t -f NAME connection show --active
      register: active_conns
      changed_when: false

    - name: Remove existing DNS, set new DNS and domain
      shell: |
        # Clear existing DNS
        nmcli connection modify "{{ item }}" ipv4.dns ""
        # Set new DNS
        nmcli connection modify "{{ item }}" ipv4.dns "{{ primary_dns }} {{ secondary_dns }}"
        # Set domain/search suffix
        nmcli connection modify "{{ item }}" ipv4.dns-search "{{ search_domain }}"
        # Ignore automatic DNS from DHCP
        nmcli connection modify "{{ item }}" ipv4.ignore-auto-dns yes
      loop: "{{ active_conns.stdout_lines }}"

    - name: Reactivate connections to apply changes
      shell: nmcli connection down "{{ item }}" && nmcli connection up "{{ item }}"
      loop: "{{ active_conns.stdout_lines }}"
