---
- name: Automated WebLogic 12.2 Installer Playbook
  hosts: all
  become: yes
  vars:
    WLS_USER: weblogic
    TARGET_DIR: /u001/software
    WEBLOGIC_HOME: /u001/wls122156/Middleware/Oracle_Home
    WEBLOGIC_URL: "https://stage.morpheusdata.com/public-archives/download/Public%20Install%20Files/fmw_12.2.1.4.0_wls_lite_Disk1_1of1.zip"
    JDK_URL: "https://stage.morpheusdata.com/public-archives/download/Public%20Install%20Files/jdk-8u202-linux-x64.tar.gz"
    SCRIPT_URL: "https://stage.morpheusdata.com/public-archives/download/Public%20Install%20Files/weblogic_script.sh"
    WEBLOGIC_FILE: fmw_12.2.1.4.0_wls_Disk1_1of1.zip
    JDK_FILE: jdk-8u202-linux-x64.tar.gz
    SCRIPT_FILE: "{{ TARGET_DIR }}/script.sh"
    JAVA_HOMEPATH: "{{ TARGET_DIR }}/jdk1.8.0_202"
    WEBLOGIC_INSTALLER_PATH: "{{ TARGET_DIR }}/fmw_12.2.1.4.0_wls_lite_generic.jar"

  tasks:

    - name: Ensure WebLogic user exists
      ansible.builtin.user:
        name: "{{ WLS_USER }}"
        shell: /sbin/nologin
        create_home: yes

    - name: Ensure directories exist with correct permissions
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        mode: '0755'
        recurse: yes
      loop:
        - "{{ WEBLOGIC_HOME }}"
        - "/u001/wls122156"
        - "{{ TARGET_DIR }}"
        - "/u001"

    - name: Download WebLogic zip
      ansible.builtin.get_url:
        url: "{{ WEBLOGIC_URL }}"
        dest: "{{ TARGET_DIR }}/{{ WEBLOGIC_FILE }}"
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        mode: '0644'

    - name: Download JDK tar.gz
      ansible.builtin.get_url:
        url: "{{ JDK_URL }}"
        dest: "{{ TARGET_DIR }}/{{ JDK_FILE }}"
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        mode: '0644'

    - name: Extract WebLogic zip
      ansible.builtin.unarchive:
        src: "{{ TARGET_DIR }}/{{ WEBLOGIC_FILE }}"
        dest: "{{ TARGET_DIR }}"
        remote_src: yes
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        extra_opts: [ "-o" ]

    - name: Extract JDK tar.gz
      ansible.builtin.unarchive:
        src: "{{ TARGET_DIR }}/{{ JDK_FILE }}"
        dest: "{{ TARGET_DIR }}"
        remote_src: yes
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        extra_opts: [ "-o" ]

    - name: Download helper installer script
      ansible.builtin.get_url:
        url: "{{ SCRIPT_URL }}"
        dest: "{{ SCRIPT_FILE }}"
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        mode: '0755'

    - name: Override JAVA_HOME and WEBLOGIC_INSTALLER in script
      ansible.builtin.replace:
        path: "{{ SCRIPT_FILE }}"
        regexp: '^JAVA_HOME=.*'
        replace: "JAVA_HOME=\"{{ JAVA_HOMEPATH }}\""

    - name: Override WEBLOGIC_INSTALLER in script
      ansible.builtin.replace:
        path: "{{ SCRIPT_FILE }}"
        regexp: '^WEBLOGIC_INSTALLER=.*'
        replace: "WEBLOGIC_INSTALLER=\"{{ WEBLOGIC_INSTALLER_PATH }}\""

    - name: Run WebLogic installer as weblogic user
      ansible.builtin.command:
        cmd: "bash {{ SCRIPT_FILE }}"
        chdir: "{{ TARGET_DIR }}"
        creates: "{{ WEBLOGIC_HOME }}/wlserver"
      become_user: "{{ WLS_USER }}"
