---
- name: Automated WebLogic 12.2 Installer Playbook
  hosts: all
  become: yes

  vars:
    WEBLOGIC_VERSION: "fmw_12.2.1.4.0_wls_lite_Disk1_1of1.zip"
    JAVA_VERSION: "jdk-8u202-linux-x64.tar.gz"
    WLS_USER: weblogic
    TARGET_DIR: /u001/software
    WEBLOGIC_HOME: /u001/wls122156/Middleware/Oracle_Home
    WEBLOGIC_URL: "https://azmphqaedge.astrazeneca.net/public-archives/download/Artifact/{{WEBLOGIC_VERSION}}"
    JDK_URL: "https://azmphqaedge.astrazeneca.net/public-archives/download/Artifact/{{JAVA_VERSION}}"                                                                                                                                           
    SCRIPT_URL: "https://azmphqaedge.astrazeneca.net/public-archives/download/Artifact/weblogic_script.sh"

    WEBLOGIC_FILE: {{WEBLOGIC_VERSION}}
    JDK_FILE: {{JAVA_VERSION}}
    SCRIPT_FILE: "{{ TARGET_DIR }}/script.sh"
    JAVA_HOMEPATH: "{{ TARGET_DIR }}/jdk1.8.0_202"
    WEBLOGIC_INSTALLER_PATH: "{{ TARGET_DIR }}/fmw_12.2.1.4.0_wls_lite_generic.jar"

  tasks:

    - name: Ensure unzip and tar utilities are installed
      ansible.builtin.package:
        name:
          - unzip
          - tar
        state: present

    - name: Create WebLogic user
      ansible.builtin.user:
        name: "{{ WLS_USER }}"
        shell: /sbin/nologin
        create_home: yes

    - name: Ensure required directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        mode: "0755"
      loop:
        - "{{ TARGET_DIR }}"
        - "{{ WEBLOGIC_HOME }}"
        - /u001/wls122156
        - /u001

    - name: Download WebLogic installation zip
      ansible.builtin.get_url:
        url: "{{ WEBLOGIC_URL }}"
        dest: "{{ TARGET_DIR }}/{{ WEBLOGIC_FILE }}"
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        validate_certs: no

    - name: Download JDK tar.gz
      ansible.builtin.get_url:
        url: "{{ JDK_URL }}"
        dest: "{{ TARGET_DIR }}/{{ JDK_FILE }}"
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        validate_certs: no

    - name: Extract WebLogic zip (safe, low memory)
      ansible.builtin.command:
        cmd: "unzip -o {{ TARGET_DIR }}/{{ WEBLOGIC_FILE }} -d {{ TARGET_DIR }}"
      become_user: "{{ WLS_USER }}"
      args:
        creates: "{{ TARGET_DIR }}/fmw_12.2.1.4.0_wls_lite_generic.jar"

    - name: Extract JDK (safe, low memory)
      ansible.builtin.command:
        cmd: "tar -xzf {{ TARGET_DIR }}/{{ JDK_FILE }} -C {{ TARGET_DIR }}"
      become_user: "{{ WLS_USER }}"
      args:
        creates: "{{ JAVA_HOMEPATH }}"

    - name: Download helper installer script
      ansible.builtin.get_url:
        url: "{{ SCRIPT_URL }}"
        dest: "{{ SCRIPT_FILE }}"
        mode: "0755"
        owner: "{{ WLS_USER }}"
        group: "{{ WLS_USER }}"
        validate_certs: no

    - name: Update JAVA_HOME in script
      ansible.builtin.replace:
        path: "{{ SCRIPT_FILE }}"
        regexp: '^JAVA_HOME=.*'
        replace: 'JAVA_HOME="{{ JAVA_HOMEPATH }}"'

    - name: Update WEBLOGIC_INSTALLER in script
      ansible.builtin.replace:
        path: "{{ SCRIPT_FILE }}"
        regexp: '^WEBLOGIC_INSTALLER=.*'
        replace: 'WEBLOGIC_INSTALLER="{{ WEBLOGIC_INSTALLER_PATH }}"'

    - name: Run WebLogic installer
      ansible.builtin.command:
        cmd: "bash {{ SCRIPT_FILE }}"
      become_user: "{{ WLS_USER }}"
      args:
        chdir: "{{ TARGET_DIR }}"
        creates: "{{ WEBLOGIC_HOME }}/wlserver"
