---
- name: Automated WebLogic 12.2 Installer
  hosts: weblogic_servers
  become: yes
  gather_facts: yes

  vars:
    weblogic_user: weblogic
    target_dir: /u001/software
    weblogic_home: /u001/wls122156/Middleware/Oracle_Home
    weblogic_file: fmw_12.2.1.4.0_wls_Disk1_1of1.zip
    jdk_file: jdk-8u202-linux-x64.tar.gz
    script_file: script.sh
    java_homepath: /u001/software/jdk1.8.0_202
    weblogic_installer_path: /u001/software/fmw_12.2.1.4.0_wls_lite_generic.jar

    weblogic_url: "https://stage.morpheusdata.com/public-archives/download/Public%20Install%20Files/fmw_12.2.1.4.0_wls_lite_Disk1_1of1.zip"
    jdk_url: "https://stage.morpheusdata.com/public-archives/download/Public%20Install%20Files/jdk-8u202-linux-x64.tar.gz"
    script_url: "https://stage.morpheusdata.com/public-archives/download/Public%20Install%20Files/weblogic_script.sh"

    min_weblogic_size: 579000000
    min_jdk_size: 185000000

  tasks:
    - name: Fail if unsupported OS
      fail:
        msg: "This playbook supports only RHEL 8/9 or Oracle Linux 9"
      when: not (
        (ansible_distribution == "RedHat" and ansible_distribution_major_version | int >= 8) or
        (ansible_distribution == "OracleLinux" and ansible_distribution_major_version | int >= 9)
      )

    - name: Install required packages
      package:
        name:
          - curl
          - unzip
          - tar
          - sudo
        state: present
