---
- name: Check WebLogic Setup, Version, OS, and JDK
  hosts: all
  become: yes
  vars:
    weblogic_user: weblogic
    weblogic_home: /u001/wls122156/Middleware/Oracle_Home
    expected_os: "OracleLinux"             # Expected OS name
    expected_os_version: "9"               # Expected OS major version
    expected_weblogic_version: "12.1.2.4.0" # Expected WebLogic version
    expected_jdk_version: "1.8.0"          # Expected JDK version

  tasks:

    - name: Check if WebLogic user exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ weblogic_user }}"
      register: weblogic_user_check
      ignore_errors: yes
      changed_when: false

    - name: Report WebLogic user existence
      ansible.builtin.debug:
        msg: >
          {% if  weblogic_user_check is defined and weblogic_user_check.rc == 0 %}
            WebLogic user "{{ weblogic_user }}" exists.
          {% else %}
            WebLogic user "{{ weblogic_user }}" does NOT exist.
          {% endif %}

    - name: Check if WebLogic binaries directory exists
      ansible.builtin.stat:
        path: "{{ weblogic_home }}/wlserver/server/bin"
      register: weblogic_bin

    - name: Report WebLogic binaries existence
      ansible.builtin.debug:
        msg: >
          {% if weblogic_bin.stat.exists %}
            WebLogic binaries are installed in {{ weblogic_home }}/wlserver/server/bin
          {% else %}
            WebLogic binaries NOT found in {{ weblogic_home }}/wlserver/server/bin
          {% endif %}

    - name: Check WebLogic version
      ansible.builtin.shell: |
        "{{ weblogic_home }}/wlserver/server/bin/version.sh | grep 'WebLogic Server'"
      register: weblogic_version
      when: weblogic_bin.stat.exists
      changed_when: false

    - name: Display WebLogic version
      ansible.builtin.debug:
        msg: "{{ weblogic_version.stdout_lines }}"
      when: weblogic_bin.stat.exists

    - name: Compare WebLogic version with expected
      ansible.builtin.debug:
        msg: >
          {% if expected_weblogic_version in weblogic_version.stdout %}
            WebLogic version check PASSED: Found {{ weblogic_version.stdout }}
          {% else %}
            WebLogic version check FAILED: Found {{ weblogic_version.stdout }}, expected {{ expected_weblogic_version }}
          {% endif %}
      when: weblogic_bin.stat.exists

    - name: Gather OS facts
      ansible.builtin.setup:
        filter: ansible_distribution*

    - name: Check if OS matches expected
      ansible.builtin.debug:
        msg: >
          {% if ansible_facts['ansible_distribution'] == expected_os and ansible_facts['ansible_distribution_major_version'] == expected_os_version %}
            OS check PASSED: {{ ansible_facts['ansible_distribution'] }} {{ ansible_facts['ansible_distribution_major_version'] }}
          {% else %}
            OS check FAILED: Found {{ ansible_facts['ansible_distribution'] }} {{ ansible_facts['ansible_distribution_major_version'] }}, expected {{ expected_os }} {{ expected_os_version }}
          {% endif %}

    - name: Check installed JDK version
      ansible.builtin.shell: java -version 2>&1 | head -n 1 | awk -F '"' '{print $2}'
      register: jdk_version
      changed_when: false

    - name: Compare JDK version with expected
      ansible.builtin.debug:
        msg: >
          {% if expected_jdk_version in jdk_version.stdout %}
            JDK version check PASSED: Found {{ jdk_version.stdout }}
          {% else %}
            JDK version check FAILED: Found {{ jdk_version.stdout }}, expected {{ expected_jdk_version }}
          {% endif %}
