---
- name: Check WebLogic Setup, Version, OS, and JDK
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    weblogic_user: weblogic
    weblogic_home: /u001/wls122156/Middleware/Oracle_Home

    # Determine expected OS
    expected_os: >-
      {% if morpheus['customOptions']['layoutId'] in ['584', '585'] %}
        RedHat
      {% else %}
        OracleLinux
      {% endif %}

    # Determine expected OS major version
    expected_os_version: >-
      {% if morpheus['customOptions']['layoutId'] == '584' %}
        8
      {% elif morpheus['customOptions']['layoutId'] == '585' %}
        9
      {% else %}
        UNKNOWN
      {% endif %}

    expected_weblogic_version: "{{ morpheus['customOptions']['WeblogicVersion'] }}"
    expected_jdk_version: "{{ morpheus['customOptions']['JavaVersion'] }}"

    # Map Java version file to JAVA_HOME path
    java_home_map:
      jdk-8u202-linux-x64.tar.gz: "/u001/software/jdk1.8.0_202"
      jdk-17.0.17_linux-x64_bin.tar.gz: "/u001/software/jdk-17.0.17"

    JAVA_HOME: "{{ java_home_map[expected_jdk_version] }}"

  tasks:

    - name: Check if WebLogic user exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ weblogic_user }}"
      register: weblogic_user_check
      ignore_errors: yes
      changed_when: false

    - name: Report WebLogic user existence
      ansible.builtin.debug:
        msg: >
          {% if weblogic_user_check is defined and weblogic_user_check|length > 0 %}
            WebLogic user "{{ weblogic_user }}" exists.
          {% else %}
            WebLogic user "{{ weblogic_user }}" does NOT exist.
          {% endif %}

    - name: Check if WebLogic binaries directory exists
      ansible.builtin.stat:
        path: "{{ weblogic_home }}/wlserver/server/bin"
      register: weblogic_bin

    - name: Report WebLogic binaries existence
      ansible.builtin.debug:
        msg: >
          {% if weblogic_bin.stat.exists %}
            WebLogic binaries are installed in {{ weblogic_home }}/wlserver/server/bin
          {% else %}
            WebLogic binaries NOT found in {{ weblogic_home }}/wlserver/server/bin
          {% endif %}

    - name: Check WebLogic version using WLST inline
      ansible.builtin.shell: |
        {{ weblogic_home }}/oracle_common/common/bin/wlst.sh -skipWLSModuleScanning << EOF
        print 'WebLogic version:'
        print weblogic.version.getWLVersion()
        exit()
        EOF
      register: weblogic_version
      ignore_errors: yes
      changed_when: false
      when: weblogic_bin.stat.exists

    - name: Display WebLogic version
      ansible.builtin.debug:
        msg: "{{ weblogic_version.stdout_lines }}"
      when: weblogic_bin.stat.exists

    - name: Compare WebLogic version with expected
      ansible.builtin.debug:
        msg: >
          {% if weblogic_version.stdout is defined and expected_weblogic_version in weblogic_version.stdout %}
            WebLogic version check PASSED: Found {{ weblogic_version.stdout }}
          {% else %}
            WebLogic version check FAILED: Found {{ weblogic_version.stdout | default('UNKNOWN') }}, expected {{ expected_weblogic_version }}
          {% endif %}
      when: weblogic_bin.stat.exists

    - name: Check if OS matches expected
      ansible.builtin.debug:
        msg: >
          {% set dist = ansible_facts.get('distribution', ansible_distribution) %}
          {% set dist_ver = ansible_facts.get('distribution_major_version', ansible_distribution_major_version) %}
          {% if dist == expected_os and dist_ver == expected_os_version %}
            OS check PASSED: {{ dist }} {{ dist_ver }}
          {% else %}
            OS check FAILED: Found {{ dist }} {{ dist_ver }}, expected {{ expected_os }} {{ expected_os_version }}
          {% endif %}

    - name: Check installed JDK version
      ansible.builtin.shell: >
        {{ JAVA_HOME }}/bin/java -version 2>&1 | head -n 1 | awk -F '"' '{print $2}'
      register: jdk_version
      changed_when: false

    - name: Compare JDK version with expected
      ansible.builtin.debug:
        msg: >
          {% if expected_jdk_version in jdk_version.stdout %}
            JDK version check PASSED: Found {{ jdk_version.stdout }}
          {% else %}
            JDK version check FAILED: Found {{ jdk_version.stdout }}, expected {{ expected_jdk_version }}
          {% endif %}
