---
- name: Check WebLogic Setup, Version, and OS
  hosts: weblogic_servers
  become: yes
  vars:
    weblogic_user: weblogic
    weblogic_home: /u001/wls122156/Middleware/Oracle_Home
    expected_os: "OracleLinux"        # Expected OS name
    expected_os_version: "8"          # Expected OS major version
    expected_weblogic_version: "14.1.1.0.0"  # Expected WebLogic version

  tasks:

    - name: Check if WebLogic user exists
      ansible.builtin.getent:
        database: passwd
        key: "{{ weblogic_user }}"
      register: weblogic_user_check
      ignore_errors: yes

    - name: Report WebLogic user existence
      ansible.builtin.debug:
        msg: >
          {% if weblogic_user_check.found %}
            WebLogic user "{{ weblogic_user }}" exists.
          {% else %}
            WebLogic user "{{ weblogic_user }}" does NOT exist.
          {% endif %}

    - name: Check if WebLogic binaries directory exists
      ansible.builtin.stat:
        path: "{{ weblogic_home }}/wlserver/server/bin"
      register: weblogic_bin

    - name: Report WebLogic binaries existence
      ansible.builtin.debug:
        msg: >
          {% if weblogic_bin.stat.exists %}
            WebLogic binaries are installed in {{ weblogic_home }}/wlserver/server/bin
          {% else %}
            WebLogic binaries NOT found in {{ weblogic_home }}/wlserver/server/bin
          {% endif %}

    - name: Check WebLogic version
      ansible.builtin.shell: |
        "{{ weblogic_home }}/wlserver/server/bin/version.sh | grep 'WebLogic Server'"
      register: weblogic_version
      when: weblogic_bin.stat.exists
      changed_when: false

    - name: Display WebLogic version
      ansible.builtin.debug:
        msg: "{{ weblogic_version.stdout_lines }}"
      when: weblogic_bin.stat.exists

    - name: Compare WebLogic version with expected
      ansible.builtin.debug:
        msg: >
          {% if expected_weblogic_version in weblogic_version.stdout %}
            WebLogic version check PASSED: Found {{ weblogic_version.stdout }}
          {% else %}
            WebLogic version check FAILED: Found {{ weblogic_version.stdout }}, expected {{ expected_weblogic_version }}
          {% endif %}
      when: weblogic_bin.stat.exists

    - name: Gather OS facts
      ansible.builtin.setup:
        filter: ansible_distribution*

    - name: Check if OS matches expected
      ansible.builtin.debug:
        msg: >
          {% if ansible_facts['ansible_distribution'] == expected_os and ansible_facts['ansible_distribution_major_version'] == expected_os_version %}
            OS check PASSED: {{ ansible_facts['ansible_distribution'] }} {{ ansible_facts['ansible_distribution_major_version'] }}
          {% else %}
            OS check FAILED: Found {{ ansible_facts['ansible_distribution'] }} {{ ansible_facts['ansible_distribution_major_version'] }}, expected {{ expected_os }} {{ expected_os_version }}
          {% endif %}
