---
- name: Create Tomcat base directory
  file:
    path: "/u01/Tomcat/"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "0755"

- name: Create version-specific Tomcat directory
  file:
    path: "/u01/Tomcat/Tomcat{{ tomcat_version }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "0755"

- name: Create application-specific Tomcat directory
  file:
    path: "/u01/Tomcat/tomcat-{{ app_name }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "0755"

- name: Create subdirectories for application
  file:
    path: "/u01/Tomcat/tomcat-{{ app_name }}/{{ item }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: "0755"
  loop:
    - conf
    - logs
    - temp
    - webapps
    - work
