---
- name: Ensure Java is installed
  yum:
    name: "{{ java_package }}"
    state: present

- name: Create Tomcat group
  group:
    name: "{{ tomcat_group }}"

- name: Create Tomcat user
  user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    create_home: no
    shell: /bin/false

- name: Download Tomcat archive
  get_url:
    url: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Create installation directory
  file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"

- name: Extract Tomcat archive
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify: restart tomcat

- name: Set permissions on Tomcat directory
  file:
    path: "{{ tomcat_install_dir }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: Configure systemd service for Tomcat
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify: restart tomcat

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Tomcat service
  systemd:
    name: tomcat
    enabled: yes
    state: started
