- name: Download Tomcat tarballs for RHEL/Rocky 8 and 9
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: /tmp/
    mode: '0644'
    validate_certs: false
  vars:
    tomcat_download_url: >-
      {% if tomcat_version == "11" %}
        https://downloads.apache.org/tomcat/tomcat-11/v11.0.22/bin/apache-tomcat-11.0.22.tar.gz
      {% elif tomcat_version == "10" %}
        https://downloads.apache.org/tomcat/tomcat-10/v10.1.14/bin/apache-tomcat-10.1.14.tar.gz
      {% elif tomcat_version == "9" %}
        https://downloads.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
      {% else %}
        ""
      {% endif %}
  when:
    - ansible_os_family in ["RedHat", "Rocky"]
    - ansible_distribution_major_version in ["8", "9"]
    - tomcat_version is defined
