- name: Download Tomcat
  get_url:
    url: "https://downloads.apache.org/tomcat/tomcat-11/v11.0.11/bin/apache-tomcat-{{ tomcat_full_version }}.tar.gz"
    dest: "/tmp/apache-tomcat-{{ tomcat_full_version }}.tar.gz"
    mode: '0644'

- name: Extract Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_full_version }}.tar.gz"
    dest: "/u01/Tomcat/"
    remote_src: yes
    #creates: "/u01/Tomcat/Tomcat{{ tomcat_version }}"
  notify: restart tomcat

- name: Rename Tomcat directory to match standard name
  command: mv "/u01/Tomcat/apache-tomcat-{{ tomcat_full_version }}" "/u01/Tomcat/Tomcat{{ tomcat_version }}"
  args:
    creates: "/u01/Tomcat/Tomcat{{ tomcat_version }}"
