---
- name: Update Morpheus instance with fqdn tag
  hosts: localhost
  gather_facts: no
  vars:
    morpheus_api_url: "https://morpheus.example.com/api"
    morpheus_api_token: "YOUR_API_TOKEN"
    morpheus_instance_id: "123"   # Pass in as extra var or lookup

  tasks:
    - name: Get Morpheus instance details
      uri:
        url: "{{ morpheus_api_url }}/instances/{{ morpheus_instance_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ morpheus_api_token }}"
        return_content: yes
        validate_certs: false
      register: morpheus_instance

    - name: Extract instance and domain
      set_fact:
        instance_name: "{{ morpheus_instance.json.instance.name }}"
        domain_name: "{{ morpheus_instance.json.instance.networkDomain }}"
        fqdn: "{{ instance_name }}.{{ domain_name }}"

    - name: Update Morpheus instance with fqdn tag
      uri:
        url: "{{ morpheus_api_url }}/instances/{{ morpheus_instance_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          instance:
            tags:
              fqdn: "{{ fqdn }}"
        status_code: 200
        validate_certs: false
      register: update_response

    - name: Debug update response
      debug:
        var: update_response.json
