---
- name: Tag vCenter VM with FQDN from Morpheus
  hosts: localhost
  gather_facts: no
  vars:
    morpheus_api_url: "https://morpheus.example.com/api"
    morpheus_api_token: "YOUR_API_TOKEN"
    vcenter_hostname: "vcenter.example.com"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "YOUR_VCENTER_PASSWORD"
    validate_certs: false

  tasks:
    - name: Get Morpheus instance details
      uri:
        url: "{{ morpheus_api_url }}/instances/{{ morpheus_instance_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ morpheus_api_token }}"
        return_content: yes
        validate_certs: false
      register: morpheus_instance

    - name: Extract instance and domain
      set_fact:
        instance_name: "{{ morpheus_instance.json.instance.name }}"
        domain_name: "{{ morpheus_instance.json.instance.networkDomain }}"
        fqdn: "{{ morpheus_instance.json.instance.name }}.{{ morpheus_instance.json.instance.networkDomain }}"

    - name: Tag VM in vCenter with fqdn
      community.vmware.vmware_guest_custom_attributes:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ instance_name }}"   # VM name in vCenter must match
        folder: "/Datacenter/vm"
        attributes:
          - name: fqdn
            value: "{{ fqdn }}"
