---
- name: Update Morpheus instance with fqdn tag
  hosts: all
  gather_facts: no
  vars:
    morpheus_api_url: "https://10.32.20.128/"
    morpheus_api_token: "{{ lookup('cypher','secret/accesstoken') | password_hash('sha512') }}"
    morpheus_instance_id: "{{ morpheus['instance']['id'] }}"   # Pass in as extra var or lookup
    morpheus_instance_name: "{{ morpheus['instance']['name'] }}"
    domainName: "{{ morpheus['instance']['domainName'] }}"
    fqdn: "{{ morpheus_instance_name }}.{{  domainName }}"

  tasks:
    - name: Update Morpheus instance with fqdn tag
      uri:
        url: "{{ morpheus_api_url }}/instances/{{ morpheus_instance_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ morpheus_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          instance:
            tags:
              fqdn: "{{ fqdn }}"
        status_code: 200
        validate_certs: false
      register: update_response

    - name: Debug update response
      debug:
        var: update_response.json
