---
- name: Update Morpheus instance with fqdn tag
  hosts: all
  gather_facts: no
  vars:
    morpheus_api_url: "https://10.32.20.128/api"
    morpheus_api_token: "{{ lookup('cypher','secret=secret/accesstoken') }}"
    morpheus_instance_id: "{{ morpheus['instance']['id'] }}"   # Pass in as extra var or lookup
    morpheus_instance_name: "{{ morpheus['instance']['name'] }}"
    domainName: "{{ morpheus['instance']['domainName'] }}"
    fqdn: "{{ morpheus_instance_name }}.{{  domainName }}"

  tasks:
    - name: Update fqdn tag (curl)
      ansible.builtin.command: >
        curl -k -X PUT
        -H "Authorization: Bearer {{ morpheus_api_token }}"
        -H "Content-Type: application/json"
        -d '{"instance":{"tags":{"fqdn":"{{ fqdn }}"}}}'
        {{ morpheus_api_url }}/instances/{{ morpheus_instance_id }}
      register: update_response

    - name: Debug API response
      debug:
        var: update_response.stdout
