---
- hosts: all
  gather_facts: true
  vars:
   postgrevsersion : "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['PostgresVer'] }}"
  tasks:
    - name: Dump All hostvars for this instance
      debug:
        msg: "{{ hostvars[inventory_hostname] | to_nice_yaml }}"
    
    - name: Dump morpheus variable for this instance
      debug:
        var: postgrevsersion
   
    
        
