---
- hosts: all
  gather_facts: true
  
  tasks:
    - name: Dump All hostvars for this instance
      debug:
        msg: "{{ hostvars[inventory_hostname] | to_nice_yaml }}"
    
    - name: Dump morpheus variable for this instance
      debug:
        msg: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['input9'] | to_nice_yaml }}"
   
    
        
