---
- name: Install and Configure MongoDB on Ubuntu
  hosts: all
  become: yes
  vars:
    mongodb_version: "6.0"  # Adjust version as needed

  tasks:
    - name: Add MongoDB GPG key
      ansible.builtin.apt_key:
      url: https://pgp.mongodb.com/server-6.0.asc
      state: present

    - name: Add MongoDB repository
      ansible.builtin.apt_repository:
       repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/6.0 multiverse"
       state: present

    - name: Update apt cache
      ansible.builtin.apt:
       update_cache: yes
  

    - name: Install MongoDB package
      when: ansible_distribution == "Ubuntu"
      apt:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      when: ansible_distribution == "Ubuntu"
      service:
        name: mongod
        state: started
        enabled: yes
