---
- name: Install and Configure MongoDB
  hosts: all
  become: yes
  vars:
    mongodb_version: "6.0"  # Adjust version as needed

  tasks:
    - name: Determine OS distribution
      ansible.builtin.setup:
        filter: ansible_distribution

    - name: Add MongoDB repository for Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt_repository:
        repo: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu/dist/ {{ ansible_lsb.codename }}/ mongodb-org {{ mongodb_version }}'
        state: present
        filename: mongodb

    - name: Add MongoDB repository for Red Hat/CentOS
      when: ansible_distribution == "RedHat"
      yum_repository:
        name: mongodb-org-{{ mongodb_version }}
        description: MongoDB {{ mongodb_version }} Repository
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/$basearch/
        gpgcheck: 1
        gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
        enabled: 1

    - name: Install MongoDB package
      apt:
        name: mongodb-org
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install MongoDB package
      yum:
        name: mongodb-org
        state: present
      when: ansible_distribution == "RedHat"

    - name: Start and enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes

   
        
