---
- name: Install MongoDB on Red Hat/CentOS and Ubuntu
  hosts: all
  become: yes

  
  tasks:
    - name: Install MongoDB on Ubuntu
      when: ansible_os_family == "Ubuntu"
      apt:
        name: mongodb
        state: present
        update_cache: yes

    - name: Add MongoDB repository for Ubuntu
      when: ansible_os_family == "Ubuntu"
      apt_repository:
        repo: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_lsb.codename }} mongodb-org 6.0'
        state: present
        filename: mongodb

    - name: Install MongoDB on Red Hat/CentOS
      when: ansible_os_family == "RedHat"
      yum:
        name: mongodb-org
        state: present

    - name: Add MongoDB repository for Red Hat/CentOS
      when: ansible_os_family == "RedHat"
      yum_repository:
        name: mongodb-org-6.0
        description: MongoDB 6.0 Repository
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/$basearch/
        gpgcheck: 1
        gpgkey: https://www.mongodb.org/static/pgp/server-6.0.asc
        enabled: 1

    - name: Start and enable MongoDB service
      service:
        name: mongod
        state: started
        enabled: yes
