---
- name: Install and configure python package
  hosts: all
  become: true
   
  tasks:
    - name: Install psycopg2
      ansible.builtin.yum:
       name: python3-psycopg2
       state: present
      when: ansible_os_family == "RedHat"

    - name: Install psycopg2
      ansible.builtin.apt:
       name: python3-psycopg2
       state: present
      when: ansible_os_family == "Debian"
