---
- name: Install and Configure MongoDB on Ubuntu
  hosts: all
  become: yes
  vars:
    mongodb_version: "6.0"  # Adjust version as needed

  tasks:    
    - name: Add MongoDB repository for Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt_repository:
        repo: 'deb [ arch=amd64 signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg ] https://repo.mongodb.org/apt/ubuntu {{ ansible_lsb.codename }} mongodb-org {{ mongodb_version }}'
        state: present
        filename: mongodb
        
    - name: Import MongoDB public GPG key
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt_key:
        url: 'https://www.mongodb.org/static/pgp/server-6.0.asc'
        state: present
        keyring: /usr/share/keyrings/mongodb-archive-keyring.gpg
        
    - name: Update APT cache
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    - name: Install MongoDB package
      when: ansible_distribution == "Ubuntu"
      apt:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB service
      when: ansible_distribution == "Ubuntu"
      service:
        name: mongod
        state: started
        enabled: yes
