---
- name: Install and configure PostgreSQL
  hosts: all
  become: true
  vars:
    postgresql_version: 15
    postgresql_data_dir: /var/lib/pgsql/{{ postgresql_version }}/data
    postgresql_service: postgresql-{{ postgresql_version }}
    
          
    - name: Add PostgreSQL APT repository key for Ubuntu
      when: ansible_facts['os_family'] == 'Debian'
      apt_key:
        url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
        state: present

    - name: Install PostgreSQL for Ubuntu
      when: ansible_facts['os_family'] == 'Debian'
      apt:
        name: postgresql-{{ postgresql_version }}
        state: present
        update_cache: yes
    

    - name: Ensure PostgreSQL service is running and enabled on Debian/Ubuntu
      ansible.builtin.systemd:
        name: postgresql
        enabled: yes
        state: started
      when: ansible_os_family == "Debian" 

    
