---
- name: Install and configure PostgreSQL
  hosts: all
  become: true
  vars:
    postgresql_version: 15
    postgresql_data_dir: /var/lib/pgsql/{{ postgresql_version }}/data
    postgresql_service: postgresql-{{ postgresql_version }}
  
  tasks:        
    - name: Print the ansible_os_family fact
      ansible.builtin.debug:
        msg: "The OS family is: {{ ansible_os_family }}"
    - name: Install PostgreSQL GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG
    - name: Install PostgreSQL repository
      ansible.builtin.yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install PostgreSQL
      ansible.builtin.yum:
        name: 
          - postgresql{{ postgresql_version }}
          - postgresql{{ postgresql_version }}-server
          - postgresql{{ postgresql_version }}-contrib
        state: present
      when: ansible_os_family == "RedHat"

    - name: Initialize PostgreSQL Database
      ansible.builtin.command: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb"
      when: ansible_os_family == "RedHat"

    - name: Ensure PostgreSQL service is running and enabled
      ansible.builtin.systemd:
        name: "{{ postgresql_service }}"
        enabled: yes
        state: started
     
    - name: Set up PostgreSQL repository for Ubuntu
      lineinfile:
        path: /etc/apt/sources.list.d/pgdg.list
        line: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        create: true
      when: ansible_facts['os_family'] == 'Debian'
      
        
    - name: Add PostgreSQL APT repository key for Ubuntu
      when: ansible_facts['os_family'] == 'Debian'
      apt_key:
        url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
        state: present

    - name: Install PostgreSQL for Ubuntu
      when: ansible_facts['os_family'] == 'Debian'
      apt:
        name: postgresql-{{ postgresql_version }}
        state: present
        update_cache: yes

    
