---
- name: Update PostgreSQL admin user password using peer authentication
  hosts: all
  become: yes
  become_user: postgres  # Ensure Ansible becomes the postgres OS user
  gather_facts: yes
  tasks:
    
      
    - name: Ensure PostgreSQL admin user password is updated
      community.postgresql.postgresql_user:
        name: postgres  # PostgreSQL admin user
        password: "{{ new_password }}"  # New password to set
        login_host: "{{ ansible_facts.hostname }}"
        login_user: postgres
        login_password: ""
        login_port: 5432
        state: present
      vars:
        new_password: "test123"  # New password for the PostgreSQL admin user
