---
- name: Update PostgreSQL user password
  hosts: db_servers
  become: yes
  vars:
    db_user: your_user        # Replace with the PostgreSQL username
    new_password: "new_secure_password"  # Replace with the new password
    postgres_host: localhost  # PostgreSQL host
    postgres_port: 5432       # PostgreSQL port (default is 5432)
    postgres_admin_user: postgres  # PostgreSQL superuser
    postgres_admin_password: "admin_password"  # Superuser password

  tasks:
    - name: Ensure PostgreSQL user password is updated
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ new_password }}"
        login_user: "{{ postgres_admin_user }}"
        login_password: "{{ postgres_admin_password }}"
        login_host: "{{ postgres_host }}"
        login_port: "{{ postgres_port }}"
        state: present
