---
- name: Test becoming postgres user
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Check if we can become postgres user
      command: whoami
      register: result

    - name: Print the result
      debug:
        msg: "The current user is {{ result.stdout }}"
