# Filesystem & Tomcat variables
mount_point: /u01
tomcat_root_dir: "{{ mount_point }}/Tomcat"
tomcat_version:  "{{ morpheus['customOptions']['tomcatVersion'] }}"
#tomcat_full_version: "11.0.12"
app_name: crm

tomcat_disk: /dev/sdb           # Change according to your environment
partition_number: 1
partition_path: "{{ tomcat_disk }}{{ partition_number }}"
vg_name: vg_tomcat
lv_name: lv_tomcat
lv_size: "{{ morpheus['customOptions']['tomcatDatasize'] }}G" 
mount_point: /u01/Tomcat
filesystem_type: xfs


# Filesystem (LVM) variables
vg_name: vg_data
lv_name: lv_u01
disk_device: /dev/sda
size: 50G
filesystem_type: xfs

# Tomcat ownership
tomcat_user: tomcat
tomcat_group: tomcat
#dir_mode: "0755"


# Java variables
java_package: "{{ morpheus['customOptions']['javaVersion'] }}"
java_home: "/u01/Tomcat/java"

#extracted_dir: "jdk-17.0.2"

extracted_dir: >-
    {{ (
      "jdk-17.0.2" if java_package== "17"
      else "jdk-21.0.2" if java_package == "21"
      else "java-se-8u44-ri" if java_package == "8"
      ) | trim }}
java_download_url: >-
    {{ (
      "https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz" if java_package== "17"
      else "https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-x64_bin.tar.gz" if java_package == "21"
      else "https://download.java.net/openjdk/jdk8u44/ri/openjdk-8u44-linux-x64.tar.gz" if java_package == "8"
       ) | trim }}
tarball_name: >-
    {{ (
      "openjdk-17.0.2_linux-x64_bin.tar.gz" if java_package== "17"
      else "openjdk-21.0.2_linux-x64_bin.tar.gz" if java_package == "21"
      else "openjdk-8u44-linux-x64.tar.gz" if java_package == "8"
         ) | trim }}    

tomcat_full_version: >-
    {{ (
      "11.0.13" if tomcat_version == "11"
      else "10.1.48" if tomcat_version == "10"
      else "9.0.111" if tomcat_version == "9"
      else ""
    ) | trim }}

tomcat_download_url: >-
    {{ (
      "https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.13/bin/apache-tomcat-11.0.13.tar.gz" if tomcat_version == "11"
      else "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.48/bin/apache-tomcat-10.1.48.tar.gz" if tomcat_version == "10"
      else "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.111/bin/apache-tomcat-9.0.111.tar.gz" if tomcat_version == "9"
      else ""
    ) | trim }}


#owner_user: tomcat
#owner_group: tomcat
