---
- name: Create Change Request and wait for approval
  hosts: all
  gather_facts: no
  vars:
    servicenow_instance: "{{ lookup('cypher','secret=secret/snowinstance')}}"
    servicenow_user: "admin"
    servicenow_password: "{{ lookup('cypher','secret=secret/snowpass') }}"
    change_request_payload:
      short_description: "Update Apache Server"
      description: "Updating Apache server to latest stable version"
      category: "{{ morpheus['customOptions']['CrCategory'] }}"
      priority: "{{ morpheus['customOptions']['CrPriority'] }}""
      risk: "{{ morpheus['customOptions']['CrRisk'] }}"
      type: "{{ morpheus['customOptions']['CrType'}}"
    polling_interval: 60  # seconds
    max_retries: 30       # total wait time = polling_interval * max_retries

  tasks:

    - name: Create a Change Request in ServiceNow
      uri:
        url: "https://{{ servicenow_instance }}.service-now.com/api/now/table/change_request"
        method: POST
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body: "{{ change_request_payload }}"
        status_code: 201
      register: create_response

    - name: Extract CR sys_id
      set_fact:
        cr_sys_id: "{{ create_response.json.result.sys_id }}"
    - name: Wait until the Change Request is approved
      uri:
        url: "https://{{ servicenow_instance }}.service-now.com/api/now/table/change_request/{{ cr_sys_id }}"
        method: GET
        user: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
      register: cr_status
      until: cr_status.json.result.state == "3"   # "3" = Approved in ServiceNow by default
      retries: "{{ max_retries }}"
      delay: "{{ polling_interval }}"

    - name: Display CR approved status
      debug:
        msg: "Change Request {{ cr_sys_id }} is approved!"     

   
